language: python
python:
  - "3.5"

notifications:
  email: false

services:
  - docker

install:
  - docker pull araffin/stable-baselines-cpu:v2.7.0

script:
  - ./run_tests_travis.sh

matrix:
  include:
    - name: "Unit Tests"


    - name: "Sphinx Documentation"
      script:
        - 'docker run -it --rm --mount src=$(pwd),target=/root/code/stable-baselines,type=bind araffin/stable-baselines-cpu bash -c "cd /root/code/stable-baselines/ && pip install .[docs] && pushd docs/ && make clean && make html"'
